spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://10.140.0.5:3306/sakila
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 60000
      
      
spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 10.140.0.5
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 10.3.254.197
  port: 5672
  username: guest
  password: wzwhNRHyg1TM
  connection-timeout: 30000


management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
      